// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJtE0Gh9qvm4G326Q_DNmi8qgslZCNaFE',
    appId: '1:703276097975:web:d6ea75c773a4ac317dc832',
    messagingSenderId: '703276097975',
    projectId: 'lipidwise-ai-hack',
    authDomain: 'lipidwise-ai-hack.firebaseapp.com',
    storageBucket: 'lipidwise-ai-hack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdt8ogY9Q2ZeHX6WigfyF4wQRx21DHZLg',
    appId: '1:703276097975:android:27a5ca3bdff5f55c7dc832',
    messagingSenderId: '703276097975',
    projectId: 'lipidwise-ai-hack',
    storageBucket: 'lipidwise-ai-hack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Rcf4shQwolyGRHQKSjq6PnSsxuUcT1Q',
    appId: '1:703276097975:ios:e493b346df668b3e7dc832',
    messagingSenderId: '703276097975',
    projectId: 'lipidwise-ai-hack',
    storageBucket: 'lipidwise-ai-hack.firebasestorage.app',
    iosBundleId: 'com.example.lipidwiseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Rcf4shQwolyGRHQKSjq6PnSsxuUcT1Q',
    appId: '1:703276097975:ios:e493b346df668b3e7dc832',
    messagingSenderId: '703276097975',
    projectId: 'lipidwise-ai-hack',
    storageBucket: 'lipidwise-ai-hack.firebasestorage.app',
    iosBundleId: 'com.example.lipidwiseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJtE0Gh9qvm4G326Q_DNmi8qgslZCNaFE',
    appId: '1:703276097975:web:ac2969fb27ae20fe7dc832',
    messagingSenderId: '703276097975',
    projectId: 'lipidwise-ai-hack',
    authDomain: 'lipidwise-ai-hack.firebaseapp.com',
    storageBucket: 'lipidwise-ai-hack.firebasestorage.app',
  );
}
