import 'package:flutter/material.dart';

class DashboardScreen extends StatelessWidget {
  final Map<String, dynamic> result;
  final String role;
  
  const DashboardScreen({super.key, required this.result, required this.role});

  Color _getRiskColor(String category) {
    if (category == 'Emergency' || category == 'Very High' || category == 'High') return const Color(0xFFDC2626); // red-600
    if (category == 'Moderate') return const Color(0xFFD97706); // amber-600
    return const Color(0xFF10B981); // emerald-500
  }

  Color _getRiskBgColor(String category) {
    if (category == 'Emergency' || category == 'Very High' || category == 'High') return const Color(0xFFFEF2F2); // red-50
    if (category == 'Moderate') return const Color(0xFFFFFBEB); // amber-50
    return const Color(0xFFECFDF5); // emerald-50
  }

  Widget _buildLipidCard(String title, double? value, double target, bool isHdl) {
    bool isBad = false;
    if (value != null) {
      if (isHdl) {
         isBad = value < target;
      } else {
         isBad = value > target;
      }
    }

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFF1F5F9)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(title, style: const TextStyle(fontWeight: FontWeight.w600, color: Color(0xFF64748B))),
              Icon(isBad ? Icons.cancel : Icons.check_circle, color: isBad ? const Color(0xFFDC2626) : const Color(0xFF10B981), size: 20),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            crossAxisAlignment: CrossAxisAlignment.baseline,
            textBaseline: TextBaseline.alphabetic,
            children: [
              Text(value?.toStringAsFixed(0) ?? '--', style: const TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Color(0xFF1E293B))),
              const SizedBox(width: 4),
              const Text('mg/dL', style: TextStyle(color: Color(0xFF94A3B8), fontSize: 12)),
            ],
          ),
          const SizedBox(height: 12),
          LinearProgressIndicator(
            value: value == null ? 0 : (value / (target * 2)).clamp(0.0, 1.0),
            backgroundColor: const Color(0xFFF1F5F9),
            color: isBad ? const Color(0xFFDC2626) : const Color(0xFF10B981),
            minHeight: 6,
            borderRadius: BorderRadius.circular(3),
          )
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    Color riskColor = _getRiskColor(result['category'] ?? 'Low');
    Color riskBgColor = _getRiskBgColor(result['category'] ?? 'Low');
    
    bool isRuleBased = result['typeBadge']?.toString().contains('Clinical') ?? false;
    List<dynamic> breakdown = result['breakdown'] ?? [];

    return SingleChildScrollView(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('Patient Risk Analysis', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Color(0xFF0F172A))),
                  const SizedBox(height: 4),
                  Text('Generated by LipidWise AI Engine', style: TextStyle(color: Colors.grey.shade600)),
                ],
              ),
              ElevatedButton.icon(
                icon: const Icon(Icons.print, size: 18),
                label: const Text('Export'),
                onPressed: () {},
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF1E293B),
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                ),
              )
            ],
          ),
          const SizedBox(height: 24),
          
          // Alert Banner
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: riskBgColor,
              borderRadius: BorderRadius.circular(16),
              border: Border(left: BorderSide(color: riskColor, width: 4)),
            ),
            child: Row(
              children: [
                CircleAvatar(
                  backgroundColor: riskColor.withOpacity(0.1),
                  child: Icon(Icons.info_outline, color: riskColor),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        '${result['category']} Concern',
                        style: TextStyle(color: riskColor, fontWeight: FontWeight.bold, fontSize: 18),
                      ),
                      const SizedBox(height: 4),
                      Text(result['message'] ?? '', style: TextStyle(color: riskColor.withOpacity(0.8))),
                    ],
                  ),
                )
              ],
            ),
          ),
          const SizedBox(height: 24),

          // 2026 ACC/AHA Key Recommendation Highlights
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: const Color(0xFFE2E8F0)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: const [
                    Icon(Icons.verified, color: Color(0xFF4F46E5), size: 22),
                    SizedBox(width: 8),
                    Text('2026 ACC/AHA Key Recommendation Highlights', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Color(0xFF0F172A))),
                  ],
                ),
                const SizedBox(height: 16),
                Wrap(
                  spacing: 12,
                  runSpacing: 12,
                  children: [
                    // PREVENT Risk Card
                    if (result['preventRisk'] != null)
                      Container(
                        width: 250,
                        padding: const EdgeInsets.all(14),
                        decoration: BoxDecoration(
                          color: const Color(0xFFF8FAFC),
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: const Color(0xFFE2E8F0)),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text('PREVENT™ Risk Score', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
                            const SizedBox(height: 4),
                            Text('10-Yr Risk: ${result['preventRisk']['label10Yr']}', style: const TextStyle(fontSize: 12, color: Color(0xFF334155))),
                            Text('30-Yr Risk: ${result['preventRisk']['label30Yr']}', style: const TextStyle(fontSize: 12, color: Color(0xFF334155))),
                            const SizedBox(height: 4),
                            Text(result['preventRisk']['status'], style: const TextStyle(fontSize: 11, fontWeight: FontWeight.w600, color: Color(0xFF0284C7))),
                          ],
                        ),
                      ),

                    // Lp(a) Card
                    if (result['lpaAssessment'] != null)
                      Container(
                        width: 250,
                        padding: const EdgeInsets.all(14),
                        decoration: BoxDecoration(
                          color: const Color(0xFFF8FAFC),
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: const Color(0xFFE2E8F0)),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text('Lipoprotein(a) [Lp(a)]', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
                            const SizedBox(height: 4),
                            Text(result['lpaAssessment']['recommendation'], style: TextStyle(fontSize: 11, color: result['lpaAssessment']['isHigh'] == true ? const Color(0xFFDC2626) : const Color(0xFF475569))),
                          ],
                        ),
                      ),

                    // CAC Card
                    if (result['cacRecommendation'] != null)
                      Container(
                        width: 250,
                        padding: const EdgeInsets.all(14),
                        decoration: BoxDecoration(
                          color: const Color(0xFFFFFBEB),
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: const Color(0xFFFDE68A)),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text('CAC Scoring Guidance', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: Color(0xFFB45309))),
                            const SizedBox(height: 4),
                            Text(result['cacRecommendation']['details'], style: const TextStyle(fontSize: 11, color: Color(0xFF92400E))),
                          ],
                        ),
                      ),

                    // LLT Escalation Card
                    if (result['therapyEscalation'] != null)
                      Container(
                        width: 250,
                        padding: const EdgeInsets.all(14),
                        decoration: BoxDecoration(
                          color: const Color(0xFFFEF2F2),
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: const Color(0xFFFCA5A5)),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text('Clinical ASCVD Therapy Escalation', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: Color(0xFF991B1B))),
                            const SizedBox(height: 4),
                            Text(result['therapyEscalation']['guidelineAdvice'], style: const TextStyle(fontSize: 11, color: Color(0xFFB91C1C))),
                          ],
                        ),
                      ),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),

          LayoutBuilder(
            builder: (context, constraints) {
              bool isWide = constraints.maxWidth > 800;
              return Flex(
                direction: isWide ? Axis.horizontal : Axis.vertical,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Gauge Card
                  Expanded(
                    flex: isWide ? 1 : 0,
                    child: Container(
                      padding: const EdgeInsets.all(24),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(color: const Color(0xFFF1F5F9)),
                      ),
                      child: Column(
                        children: [
                          const Align(
                            alignment: Alignment.topLeft,
                            child: Text('ASSESSMENT MODE', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Color(0xFF94A3B8))),
                          ),
                          Align(
                            alignment: Alignment.topLeft,
                            child: Container(
                              margin: const EdgeInsets.only(top: 8, bottom: 24),
                              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                              decoration: BoxDecoration(
                                color: const Color(0xFFEEF2FF),
                                borderRadius: BorderRadius.circular(6),
                                border: Border.all(color: const Color(0xFFE0E7FF)),
                              ),
                              child: Text(result['typeBadge'] ?? '', style: const TextStyle(color: Color(0xFF4338CA), fontSize: 12, fontWeight: FontWeight.bold)),
                            ),
                          ),
                          SizedBox(
                            height: 150,
                            width: 150,
                            child: Stack(
                              children: [
                                const Center(
                                  child: SizedBox(
                                    width: 150, height: 150,
                                    child: CircularProgressIndicator(value: 1, color: Color(0xFFF1F5F9), strokeWidth: 12),
                                  ),
                                ),
                                Center(
                                  child: TweenAnimationBuilder<double>(
                                    tween: Tween<double>(begin: 0, end: result['gaugeValue'] ?? 0.0),
                                    duration: const Duration(seconds: 1),
                                    builder: (context, value, _) => SizedBox(
                                      width: 150, height: 150,
                                      child: CircularProgressIndicator(value: value, color: riskColor, strokeWidth: 12, strokeCap: StrokeCap.round),
                                    ),
                                  ),
                                ),
                                Center(
                                  child: Text(result['category']?.split(' ').join('\n') ?? '', textAlign: TextAlign.center, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                                )
                              ],
                            ),
                          )
                        ],
                      ),
                    ),
                  ),
                  if (isWide) const SizedBox(width: 24),
                  if (!isWide) const SizedBox(height: 24),
                  
                  // Specific Lipid Breakdown OR ML Factors
                  Expanded(
                    flex: isWide ? 2 : 0,
                    child: isRuleBased
                      ? GridView.count(
                          crossAxisCount: isWide ? 2 : 2,
                          shrinkWrap: true,
                          crossAxisSpacing: 16,
                          mainAxisSpacing: 16,
                          childAspectRatio: 1.5,
                          physics: const NeverScrollableScrollPhysics(),
                          children: [
                             _buildLipidCard('LDL-C (Bad)', breakdown.isNotEmpty ? double.tryParse(breakdown.firstWhere((b) => b['marker'] == 'LDL-C')['value'].toString()) : null, 130, false),
                             _buildLipidCard('HDL-C (Good)', breakdown.isNotEmpty ? double.tryParse(breakdown.firstWhere((b) => b['marker'] == 'HDL-C')['value'].toString()) : null, 40, true),
                             _buildLipidCard('Triglycerides', breakdown.isNotEmpty ? double.tryParse(breakdown.firstWhere((b) => b['marker'] == 'Triglycerides')['value'].toString()) : null, 150, false),
                             _buildLipidCard('Total Chol', breakdown.isNotEmpty ? double.tryParse(breakdown.firstWhere((b) => b['marker'] == 'Total Cholesterol')['value'].toString()) : null, 200, false),
                          ],
                        )
                      : Container(
                          padding: const EdgeInsets.all(24),
                          decoration: BoxDecoration(
                            color: Colors.white,
                            borderRadius: BorderRadius.circular(16),
                            border: Border.all(color: const Color(0xFFF1F5F9)),
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text('Top Contributing Risk Factors', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600)),
                              const SizedBox(height: 8),
                              const Text('Since no lipid profile was provided, the AI estimated risk based on lifestyle and medical history.', style: TextStyle(color: Color(0xFF64748B), fontSize: 14)),
                              const SizedBox(height: 16),
                              if (result['topFactors'] != null)
                                ...((result['topFactors'] as List).map((f) => Padding(
                                  padding: const EdgeInsets.only(bottom: 12.0),
                                  child: Container(
                                    padding: const EdgeInsets.all(12),
                                    decoration: BoxDecoration(
                                      color: const Color(0xFFFFFBEB),
                                      border: Border.all(color: const Color(0xFFFEF3C7)),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    child: Row(
                                      children: [
                                        const Icon(Icons.circle, color: Color(0xFFF59E0B), size: 12),
                                        const SizedBox(width: 12),
                                        Text(f['name'], style: const TextStyle(fontWeight: FontWeight.w500, color: Color(0xFF92400E))),
                                      ],
                                    ),
                                  ),
                                ))),
                            ],
                          ),
                        ),
                  ),
                ],
              );
            }
          ),

          const SizedBox(height: 24),
          // AI Coach Plan
          Container(
            padding: const EdgeInsets.all(24),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: const Color(0xFFF1F5F9)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(color: const Color(0xFFF3E8FF), borderRadius: BorderRadius.circular(8)),
                      child: const Icon(Icons.smart_toy, color: Color(0xFF9333EA)),
                    ),
                    const SizedBox(width: 12),
                    const Text('AI Lifestyle Coach Plan', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Color(0xFF1E293B))),
                  ],
                ),
                const SizedBox(height: 24),
                LayoutBuilder(
                  builder: (context, constraints) {
                    bool isWide = constraints.maxWidth > 600;
                    return Flex(
                      direction: isWide ? Axis.horizontal : Axis.vertical,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(
                          flex: isWide ? 1 : 0,
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text('SMART FOOD SWAPS', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Color(0xFF94A3B8))),
                              const Divider(),
                              if (result['swaps'] != null)
                                ...((result['swaps'] as List).map((s) => Padding(
                                  padding: const EdgeInsets.only(top: 8.0, bottom: 8.0),
                                  child: Row(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      const Icon(Icons.restaurant, color: Color(0xFF3B82F6), size: 16),
                                      const SizedBox(width: 12),
                                      Expanded(
                                        child: RichText(
                                          text: TextSpan(
                                            style: const TextStyle(color: Color(0xFF334155), fontSize: 14),
                                            children: [
                                              const TextSpan(text: 'Swap '),
                                              TextSpan(text: s['from'], style: const TextStyle(decoration: TextDecoration.lineThrough)),
                                              const TextSpan(text: ' for '),
                                              TextSpan(text: s['to'], style: const TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF10B981))),
                                            ],
                                          ),
                                        ),
                                      )
                                    ],
                                  ),
                                ))),
                            ],
                          ),
                        ),
                        if (isWide) const SizedBox(width: 32),
                        if (!isWide) const SizedBox(height: 24),
                        Expanded(
                          flex: isWide ? 1 : 0,
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text('WEEKLY ACTION PLAN', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Color(0xFF94A3B8))),
                              const Divider(),
                              if (result['plan'] != null)
                                ...((result['plan'] as List).map((p) => Padding(
                                  padding: const EdgeInsets.only(top: 8.0, bottom: 8.0),
                                  child: Row(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      const Icon(Icons.check_circle_outline, color: Color(0xFF3B82F6), size: 16),
                                      const SizedBox(width: 12),
                                      Expanded(child: Text(p['desc'], style: const TextStyle(color: Color(0xFF334155), fontSize: 14))),
                                    ],
                                  ),
                                ))),
                            ],
                          ),
                        ),
                      ],
                    );
                  }
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
